app = "sr-uncensored"
primary_region = "arn"

[build]
  dockerfile = "Dockerfile"

[env]
  BASE_URL = "https://sr-restored.se"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
