name: Deploy

on:
  push:
    branches: [ "master" ]
  schedule:
    # Runs at 03:14 UTC every Saturday
    - cron: '14 3 * * 6'

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --local-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
